### ISSUE TITLE
Preprocessing for Nalu-Wind

### ISSUE THREAD

**Issue by psakievich** [psakievich/exawind-driver#23]

**Comment by psakievich** [comment]
VOF looping over a gradient 
Working on pressure implementation

**Comment by pscrozi** [comment]
Wyatt is reworking the pressure to fit the Nalu-Wind discretization. Wyatt will continue down this line, assuming it is still needed.

**Comment by pscrozi** [comment]
Put together framework for pressure implementation. One open question about pressure. We need to discuss: Phil, Michael, Wyatt. Wyatt will set up this discussion.

**Comment by pscrozi** [comment]
Wyatt is working on implementing this right now. It is using the document Wyatt sent out, starting with values from AMR-Wind and modifying it. In the end it will decouple it, so there is a concern there.

**Comment by pscrozi** [comment]
Wyatt finished putting in the pre-processing idea and modifying the pressure all at once. Seemed promising at short time scales, but at longer time scales, he found a lot of discrepancies. The interface doesn't settle at the same level on both meshes. There's a weird diff in the overset mesh. The single grid is relatively ok. Overall, it made results worse.

As a way forward, Wyatt suggests not reinitializing an entire VOF field. Solve same VOF equation and apply it to the overset nodes specifically so that it behaves the same as the interior. 

Wyatt to set up meeting and invite Michael and Phil later today (10/5).
